import { neon } from '@neondatabase/serverless';
import Stripe from 'stripe';
export const services={vocal:{name:'Vocal Tracking Session',minutes:180,aed:1800},rental4:{name:'Studio Rental — 4 hours',minutes:240,aed:2000},rental8:{name:'Studio Rental — 8 hours',minutes:480,aed:3500},voiceover:{name:'Voice Over Session',minutes:180,aed:1500},instrument:{name:'Instrument Tracking Session',minutes:180,aed:1800}};
export const sql=()=>neon(process.env.DATABASE_URL);
export const stripe=()=>new Stripe(process.env.STRIPE_SECRET_KEY);
export const site=()=>process.env.SITE_URL||'https://www.rayanstudios.ae';
export function reply(res,code,data){res.setHeader('Cache-Control','no-store');return res.status(code).json(data)}
export function parseSlot(date,time,service){const s=services[service];if(!s||!/^\d{4}-\d{2}-\d{2}$/.test(date||'')||!/^\d{2}:\d{2}$/.test(time||''))return null;const [h,m]=time.split(':').map(Number);if(m!==0&&m!==30)return null;const start=Date.parse(`${date}T${time}:00+04:00`);if(!Number.isFinite(start)||start<Date.now()+2*3600000||start>Date.now()+90*86400000)return null;const local=new Date(start+4*3600000);if(local.toISOString().slice(0,10)!==date)return null;const day=local.getUTCDay();const open=day>=1&&day<=4?720:day===5?840:day===6?780:null;const close=day>=1&&day<=5?1380:day===6?1020:null;if(open===null||h*60+m<open||h*60+m+s.minutes>close)return null;return {start:new Date(start).toISOString(),end:new Date(start+s.minutes*60000).toISOString()}}
export async function google(path,body,method){const required=['GOOGLE_CLIENT_ID','GOOGLE_CLIENT_SECRET','GOOGLE_REFRESH_TOKEN','GOOGLE_CALENDAR_ID'];for(const key of required)if(!process.env[key])throw Error('Google integration not configured');const tokenResp=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:process.env.GOOGLE_CLIENT_ID,client_secret:process.env.GOOGLE_CLIENT_SECRET,refresh_token:process.env.GOOGLE_REFRESH_TOKEN,grant_type:'refresh_token'})});if(!tokenResp.ok)throw Error('Google authorization failed');const token=(await tokenResp.json()).access_token;const response=await fetch('https://www.googleapis.com/calendar/v3/'+path,{method:method|| (body?'POST':'GET'),headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});if(!response.ok)throw Error('Google Calendar request failed: '+response.status);return response.json()}
export async function calendarFree(start,end){const id=process.env.GOOGLE_CALENDAR_ID;const data=await google('freeBusy',{timeMin:start,timeMax:end,items:[{id}]});const c=data.calendars?.[id];if(!c||c.errors?.length)throw Error('Calendar availability unavailable');return c.busy.length===0}
export async function clearExpired(){await sql()`UPDATE studio_bookings SET status='expired' WHERE status='pending' AND created_at < NOW()-INTERVAL '35 minutes'`}
export async function isFree(start,end){await clearExpired();const rows=await sql()`SELECT id FROM studio_bookings WHERE status IN ('pending','confirmed') AND start_time < ${end}::timestamptz AND end_time > ${start}::timestamptz LIMIT 1`;return rows.length===0 && await calendarFree(start,end)}
export function fail(res,e){console.error(e);return reply(res,503,{error:'Booking is temporarily unavailable. Please contact the studio.'})}
