import Stripe from 'stripe';
import {sql,google,services} from './lib/booking.js';
export const config={api:{bodyParser:false}};
async function raw(req){const chunks=[];for await(const chunk of req)chunks.push(Buffer.from(chunk));return Buffer.concat(chunks)}
export default async function handler(req,res){if(req.method!=='POST')return res.status(405).end();let event;try{const stripe=new Stripe(process.env.STRIPE_SECRET_KEY);event=stripe.webhooks.constructEvent(await raw(req),req.headers['stripe-signature'],process.env.STRIPE_WEBHOOK_SECRET)}catch(e){return res.status(400).send('Invalid signature')}
if(event.type!=='checkout.session.completed'&&event.type!=='checkout.session.async_payment_succeeded')return res.status(200).json({received:true});
const session=event.data.object;if(session.payment_status!=='paid')return res.status(200).json({received:true});
try{const db=sql();const id=Number(session.metadata?.booking_id);if(!Number.isSafeInteger(id))throw Error('Invalid booking ID');const rows=await db`SELECT * FROM studio_bookings WHERE id=${id} AND stripe_checkout_session_id=${session.id}`;if(!rows.length)throw Error('Booking not found');const b=rows[0];if(b.status==='cancelled')throw Error('Booking cancelled after payment');if(b.status==='confirmed'&&b.google_calendar_event_id)return res.status(200).json({received:true});const expected=services[b.service]?.aed*100;if(!expected||session.amount_total!==expected||session.currency!=='aed')throw Error('Payment amount mismatch');await db`UPDATE studio_bookings SET status='confirmed',stripe_payment_intent_id=${String(session.payment_intent||'')} WHERE id=${id} AND status IN ('pending','expired','confirmed')`;
if(!b.google_calendar_event_id){const calId=encodeURIComponent(process.env.GOOGLE_CALENDAR_ID);const created=await google(`calendars/${calId}/events`,{summary:`Rayan Studios — ${services[b.service].name}`,description:`Booking #${id}\nClient: ${b.customer_name}\nEmail: ${b.customer_email}\nPhone: ${b.customer_phone||''}\nStripe session: ${session.id}`,start:{dateTime:new Date(b.start_time).toISOString(),timeZone:'Asia/Dubai'},end:{dateTime:new Date(b.end_time).toISOString(),timeZone:'Asia/Dubai'}},'POST');await db`UPDATE studio_bookings SET google_calendar_event_id=${created.id} WHERE id=${id}`}
return res.status(200).json({received:true})}catch(e){console.error('Paid booking requires reconciliation',event.id,e);return res.status(500).json({error:'Retry webhook'})}}
